services:

  nginx:
    ports:
      - "443:443"
    image: nginx
    container_name: nginx
    build: requirements/nginx
    networks:
      - inception_network
    volumes:
      - "wp-volume:/var/www/html/"
    restart: always
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - "wp-volume:/var/www/html/"
    restart: always
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception_network
    build:
      context: requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_ROOT=${DB_ROOT}
        - DB_RPASS=${DB_RPASS}
    volumes:
      - "db-volume:/var/lib/mysql/"
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 888:888
    networks:
      - inception_network
    build: requirements/adminer
    restart: always
    depends_on:
      - mariadb

volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lbertran/data/wp-volume
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lbertran/data/db-volume


networks:
  inception_network:
    name: inception_network
    driver: bridge