services:

  nginx:
    ports:
      - "443:443"
      - "80:80"
    image: nginx
    container_name: nginx
    build: requirements/nginx
    volumes:
      - "wp-volume:/var/www/html/"

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - "wp-volume:/var/www/html/"

  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb



volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      device: /Users/lbertran/Desktop/work/inception/volumes