services:
  nginx:
    ports:
      - "443:443"
    image: nginx
    build: requirements/nginx
  wordpress:
    image: wordpress
    build: requirements/wordpress
  mariadb:
    image: mariadb
    build: requirements/mariadb
